CREATE TABLE Projects (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT,
    SystemId INTEGER,
    Description TEXT,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP,
    LastUpdated DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SystemId) REFERENCES Systems(ID)
);

CREATE TRIGGER update_lastUpdated_Projects
AFTER UPDATE ON Projects
FOR EACH ROW
BEGIN
   UPDATE Projects SET LastUpdated = CURRENT_TIMESTAMP WHERE ID = OLD.ID;
END;