CREATE TABLE Systems (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT,
    Description TEXT,
    Created DATETIME DEFAULT CURRENT_TIMESTAMP,
    LastUpdated DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_lastUpdated_Systems
AFTER UPDATE ON Systems
FOR EACH ROW
BEGIN
   UPDATE Systems SET LastUpdated = CURRENT_TIMESTAMP WHERE ID = OLD.ID;
END;