// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JiraLib.Models {
    /// <summary>The type of the group label.</summary>
    public enum GroupLabel_type
    {
        [EnumMember(Value = "ADMIN")]
        #pragma warning disable CS1591
        ADMIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "SINGLE")]
        #pragma warning disable CS1591
        SINGLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MULTIPLE")]
        #pragma warning disable CS1591
        MULTIPLE,
        #pragma warning restore CS1591
    }
}
