// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JiraLib.Models {
    /// <summary>The named position to which the screen tab field should be moved. Required if `after` isn&apos;t provided.</summary>
    public enum MoveFieldBean_position
    {
        [EnumMember(Value = "Earlier")]
        #pragma warning disable CS1591
        Earlier,
        #pragma warning restore CS1591
        [EnumMember(Value = "Later")]
        #pragma warning disable CS1591
        Later,
        #pragma warning restore CS1591
        [EnumMember(Value = "First")]
        #pragma warning disable CS1591
        First,
        #pragma warning restore CS1591
        [EnumMember(Value = "Last")]
        #pragma warning disable CS1591
        Last,
        #pragma warning restore CS1591
    }
}
