// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JiraLib.Models {
    /// <summary>The feature state.</summary>
    public enum ProjectFeatureState_state
    {
        [EnumMember(Value = "ENABLED")]
        #pragma warning disable CS1591
        ENABLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DISABLED")]
        #pragma warning disable CS1591
        DISABLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMING_SOON")]
        #pragma warning disable CS1591
        COMING_SOON,
        #pragma warning restore CS1591
    }
}
