// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JiraLib.Models {
    /// <summary>The format that will appear on an issue&apos;s *Time Spent* field.</summary>
    public enum TimeTrackingConfiguration_timeFormat
    {
        [EnumMember(Value = "pretty")]
        #pragma warning disable CS1591
        Pretty,
        #pragma warning restore CS1591
        [EnumMember(Value = "days")]
        #pragma warning disable CS1591
        Days,
        #pragma warning restore CS1591
        [EnumMember(Value = "hours")]
        #pragma warning disable CS1591
        Hours,
        #pragma warning restore CS1591
    }
}
