// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JiraLib.Models {
    /// <summary>The default unit of time applied to logged time.</summary>
    public enum TimeTrackingConfiguration_defaultUnit
    {
        [EnumMember(Value = "minute")]
        #pragma warning disable CS1591
        Minute,
        #pragma warning restore CS1591
        [EnumMember(Value = "hour")]
        #pragma warning disable CS1591
        Hour,
        #pragma warning restore CS1591
        [EnumMember(Value = "day")]
        #pragma warning disable CS1591
        Day,
        #pragma warning restore CS1591
        [EnumMember(Value = "week")]
        #pragma warning disable CS1591
        Week,
        #pragma warning restore CS1591
    }
}
