// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace JiraLib.Models {
    /// <summary>
    /// Update projects in a scheme
    /// </summary>
    public class UpdateProjectsInSchemeRequestBean : IAdditionalDataHolder, IParsable 
    {
        /// <summary>Projects to add to a scheme</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PrioritySchemeChangesWithoutMappings? Add { get; set; }
#nullable restore
#else
        public PrioritySchemeChangesWithoutMappings Add { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Projects to remove from a scheme</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PrioritySchemeChangesWithoutMappings? Remove { get; set; }
#nullable restore
#else
        public PrioritySchemeChangesWithoutMappings Remove { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="UpdateProjectsInSchemeRequestBean"/> and sets the default values.
        /// </summary>
        public UpdateProjectsInSchemeRequestBean()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="UpdateProjectsInSchemeRequestBean"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static UpdateProjectsInSchemeRequestBean CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new UpdateProjectsInSchemeRequestBean();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"add", n => { Add = n.GetObjectValue<PrioritySchemeChangesWithoutMappings>(PrioritySchemeChangesWithoutMappings.CreateFromDiscriminatorValue); } },
                {"remove", n => { Remove = n.GetObjectValue<PrioritySchemeChangesWithoutMappings>(PrioritySchemeChangesWithoutMappings.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<PrioritySchemeChangesWithoutMappings>("add", Add);
            writer.WriteObjectValue<PrioritySchemeChangesWithoutMappings>("remove", Remove);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
