// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JiraLib.Models {
    #pragma warning disable CS1591
    public enum WebhookDetails_events
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "jira:issue_created")]
        #pragma warning disable CS1591
        JiraIssue_created,
        #pragma warning restore CS1591
        [EnumMember(Value = "jira:issue_updated")]
        #pragma warning disable CS1591
        JiraIssue_updated,
        #pragma warning restore CS1591
        [EnumMember(Value = "jira:issue_deleted")]
        #pragma warning disable CS1591
        JiraIssue_deleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "comment_created")]
        #pragma warning disable CS1591
        Comment_created,
        #pragma warning restore CS1591
        [EnumMember(Value = "comment_updated")]
        #pragma warning disable CS1591
        Comment_updated,
        #pragma warning restore CS1591
        [EnumMember(Value = "comment_deleted")]
        #pragma warning disable CS1591
        Comment_deleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "issue_property_set")]
        #pragma warning disable CS1591
        Issue_property_set,
        #pragma warning restore CS1591
        [EnumMember(Value = "issue_property_deleted")]
        #pragma warning disable CS1591
        Issue_property_deleted,
        #pragma warning restore CS1591
    }
}
