// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JiraLib.Models {
    /// <summary>The scope of the workflow capabilities. `GLOBAL` for company-managed projects and `PROJECT` for team-managed projects.</summary>
    public enum WorkflowCapabilities_editorScope
    {
        [EnumMember(Value = "PROJECT")]
        #pragma warning disable CS1591
        PROJECT,
        #pragma warning restore CS1591
        [EnumMember(Value = "GLOBAL")]
        #pragma warning disable CS1591
        GLOBAL,
        #pragma warning restore CS1591
    }
}
