// <auto-generated/>
using JiraLib.Rest.Api;
using JiraLib.Rest.AtlassianConnect;
using JiraLib.Rest.Forge;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace JiraLib.Rest {
    /// <summary>
    /// Builds and executes requests for operations under \rest
    /// </summary>
    public class RestRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The api property</summary>
        public ApiRequestBuilder Api
        {
            get => new ApiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The atlassianConnect property</summary>
        public AtlassianConnectRequestBuilder AtlassianConnect
        {
            get => new AtlassianConnectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forge property</summary>
        public ForgeRequestBuilder Forge
        {
            get => new ForgeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="RestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="RestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RestRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest", rawUrl)
        {
        }
    }
}
