// <auto-generated/>
using JiraLib.Rest.Api.Three.Comment.Item;
using JiraLib.Rest.Api.Three.Comment.List;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace JiraLib.Rest.Api.Three.Comment {
    /// <summary>
    /// Builds and executes requests for operations under \rest\api\3\comment
    /// </summary>
    public class CommentRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The list property</summary>
        public ListRequestBuilder List
        {
            get => new ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the JiraLib.rest.api.Three.comment.item collection</summary>
        /// <param name="position">The ID of the comment.</param>
        /// <returns>A <see cref="WithCommentItemRequestBuilder"/></returns>
        public WithCommentItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("commentId", position);
                return new WithCommentItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="CommentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CommentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/comment", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="CommentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CommentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rest/api/3/comment", rawUrl)
        {
        }
    }
}
