// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JiraLib.Rest.Api.Three.Expression.Analyse {
    #pragma warning disable CS1591
    public enum PostCheckQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "syntax")]
        #pragma warning disable CS1591
        Syntax,
        #pragma warning restore CS1591
        [EnumMember(Value = "type")]
        #pragma warning disable CS1591
        Type,
        #pragma warning restore CS1591
        [EnumMember(Value = "complexity")]
        #pragma warning disable CS1591
        Complexity,
        #pragma warning restore CS1591
    }
}
